'use client';
import {useLanguage,LanguagePicker} from './language-provider';
import PlanningWorkspace,{type WorkspaceMode} from './planning-workspace';
import NowPanel,{type ReplanIntent} from './now-panel';
import FocusMode from './focus-mode';
import DayOverview from './day-overview';
import {draftInGap,editedBlockTimes,type TimeRange} from '@/lib/block-editor';
import {NextStepDialog,TimerReviewDialog,type MemoTarget,type ReviewTarget} from './recovery-controls';
import {nextStepFor,reviewDue,type TimerReview} from '@/lib/recovery';
import {focusRecord,sceneForActivity,type FocusTarget} from '@/lib/focus';
import {suggestedBlock} from '@/lib/planner-view';
import {defaults,routine} from '@/lib/planning';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {Focus,Inbox,Settings2,ArrowDown,ArrowRight,BookOpen,CalendarDays,Cat,Check,ChevronLeft,ChevronRight,Clock3,Coffee,Dumbbell,LayoutDashboard,Leaf,Loader2,Pause,Pencil,Play,Plus,RotateCcw,Save,SlidersHorizontal,Sparkles,Sun,Trash2,TrendingUp,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {NativeSelect} from '@/components/ui/native-select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from './localized-dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {clock,elapsed,getDay,hm,localEpoch,localInput,parseLocalInput,minutes,shiftDate,template,totals,daySchema,type Block,type Category,type Day,type Log,type Snapshot} from '@/lib/planner';
const icons={work:LayoutDashboard,meal:Coffee,move:Dumbbell,cat:Cat,life:Sun,rest:BookOpen};
const modeLabels={normal:'日常节奏',shopping:'买菜日',slow:'慢慢做饭',custom:'自定义'};
function clone(s:Snapshot):Snapshot{return structuredClone(s)}
function Field({label,children}:{label:string,children:React.ReactNode}){

return <label className="field"><span>{label}</span>{children}</label>}
export default function Planner(){
 const {tr,locale,duration,categories,blockTitle,blockNote,recordTitle,dateLabel}=useLanguage();

 const [memoTarget,setMemoTarget]=useState<MemoTarget|null>(null),[reviewTarget,setReviewTarget]=useState<ReviewTarget|null>(null);
 const [focusOpen,setFocusOpen]=useState(false),[focusTarget,setFocusTarget]=useState<FocusTarget|null>(null);
 const [intent,setIntent]=useState<ReplanIntent>(null);const [agendaOpen,setAgendaOpen]=useState(false);const [online,setOnline]=useState(true);const [syncing,setSyncing]=useState(false);const [undo,setUndo]=useState<{date:string,id:string,done:boolean}|null>(null);
 const [workspace,setWorkspace]=useState<WorkspaceMode>(null);const [date,setDate]=useState('');const [now,setNow]=useState(0);
 const [data,setData]=useState<Snapshot>({revision:0,active:null,days:{}});
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [view,setView]=useState('overview'),[selected,setSelected]=useState(''),[goal,setGoal]=useState('');
 const [blockDraft,setBlockDraft]=useState<Block|null>(null),[newBlock,setNewBlock]=useState(false),[deleteConfirm,setDeleteConfirm]=useState(false);
 const [logDraft,setLogDraft]=useState<{id:string,blockId:string,title:string,category:Category,start:string,end:string}|null>(null);
 const [templateOpen,setTemplateOpen]=useState(false),[mode,setMode]=useState<Day['mode']>('normal'),[formError,setFormError]=useState('');
 const loadId=useRef(0),lock=useRef(false),initialDateChecked=useRef(false);
 useEffect(()=>{setDate(clock().planDate);let timer:ReturnType<typeof setInterval>|undefined;const update=()=>{if(timer)clearInterval(timer);setNow(Date.now());if(document.visibilityState==='visible')timer=setInterval(()=>setNow(Date.now()),1000)};update();document.addEventListener('visibilitychange',update);try{const stored=JSON.parse(sessionStorage.getItem('liubai-focus-view')??'null');if(stored&&typeof stored.date==='string'&&typeof stored.id==='string'){setFocusTarget(stored);setFocusOpen(true)}}catch{}return()=>{if(timer)clearInterval(timer);document.removeEventListener('visibilitychange',update)}},[]);
 async function load(d:string){const id=++loadId.current;setLoading(true);setError('');try{const r=await fetch('/api/planner?date='+d,{cache:'no-store'});const s=await r.json();if(!r.ok)throw new Error(s.error);if(id!==loadId.current)return;if(!initialDateChecked.current){initialDateChecked.current=true;const today=clock(Date.now(),(s.settings??defaults).wake).planDate;if(d!==today){setDate(today);return}}setData(s);setGoal(getDay(s,d).goal);setSelected('')}catch(e){if(id===loadId.current)setError((e as Error).message)}finally{if(id===loadId.current)setLoading(false)}}
 useEffect(()=>{if(date)void load(date)},[date]);
 useEffect(()=>{if(!message)return;const t=setTimeout(()=>setMessage(''),8000);return()=>clearTimeout(t)},[message]);
 const settings=data.settings??defaults;const day=data.days[date]??routine(settings);const time=clock(now||Date.now(),settings.wake);const isToday=date===time.planDate;
 const previousPlanDate=useRef(time.planDate);
 useEffect(()=>{const previous=previousPlanDate.current;if(previous!==time.planDate&&!workspace&&!blockDraft&&!logDraft&&!busy&&!loading&&!memoTarget&&!reviewTarget&&goal===day.goal){previousPlanDate.current=time.planDate;if(date===previous){setLoading(true);setDate(time.planDate);setSelected('')}}},[time.planDate,date,workspace,blockDraft,logDraft,busy,loading,goal,day.goal,memoTarget,reviewTarget]);
 const current=isToday?day.blocks.find(b=>b.start<=time.planMinute&&b.end>time.planMinute):undefined;
 const active=data.active;const focus=suggestedBlock(day,time.planMinute,isToday,selected,active?.day===date?active.blockId:undefined);
 const overviewCurrent=suggestedBlock(day,time.planMinute,isToday,'',active?.day===date?active.blockId:undefined);
 const activeBlock=active?(data.days[active.day]??routine(settings)).blocks.find(b=>b.id===active.blockId):undefined;
 const shownBlock=active?activeBlock:focus;const shownDate=active?.day??date;
 const nextBase=active?.day===date?day.blocks.find(b=>b.id===active.blockId)??focus:focus;
 const next=nextBase?day.blocks.find(b=>b.start>=nextBase.end&&!b.done):undefined;
 const pinnedFallback=focusTarget?.date===date?day.blocks.find(b=>b.id===focusTarget.id):undefined;
 const focused=focusRecord(data,focusTarget,pinnedFallback);
 const focusDay=data.days[focused.date]??(focused.date===date?day:undefined);
 const focusNext=focused.block?focusDay?.blocks.find(b=>b.start>=focused.block!.end&&!b.done):undefined;
 useEffect(()=>{if(!focusOpen)return;if(active)setFocusTarget({date:active.day,id:active.blockId})},[focusOpen,active?.day,active?.blockId]);
 useEffect(()=>{try{if(focusOpen&&focusTarget)sessionStorage.setItem('liubai-focus-view',JSON.stringify(focusTarget));else sessionStorage.removeItem('liubai-focus-view')}catch{}},[focusOpen,focusTarget]);
 useEffect(()=>{document.title=active?'▶ '+recordTitle(active)+tr(" · 留白"):focusOpen&&focused.activity?(focused.done?tr("已完成"):focused.savedMs?tr("已暂停"):tr("专注"))+' · '+blockTitle(focused.block)+tr(" · 留白"):tr("留白 · Alex 的一天");return()=>{document.title=tr("留白 · Alex 的一天")}},[locale,active?.title,active?.blockId,!!active,focusOpen,focused.activity?.title,focused.done,!!focused.savedMs]);
 function openFocus(){const b=view==='overview'?overviewCurrent:focus;const target=active?{date:active.day,id:active.blockId}:b?{date,id:b.id}:null;setFocusTarget(target);setFocusOpen(true)}
 function chooseFocusTask(){setFocusOpen(false);if(date!==time.planDate)navigate(time.planDate);jump('agenda')}
 function chooseFocusNext(){if(focusNext)setFocusTarget({date:focused.date,id:focusNext.id})}
 const summary=totals(day,active,date,now);const work=summary.find(s=>s.cat==='work')!;
 const catMinutes=day.blocks.filter(b=>b.category==='cat'&&b.title.includes('玩')).reduce((s,b)=>s+b.end-b.start,0);
 const sleep=day.blocks.filter(b=>b.title==='睡眠').reduce((s,b)=>s+b.end-b.start,0);
 const weekMax=Math.max(600,...Array.from({length:7},(_,i)=>{const d=shiftDate(date||time.planDate,i-6);return totals(data.days[d]??{...template(),blocks:[]},active,d,now).find(s=>s.cat==='work')!.actual}));
 const actualTotal=summary.reduce((s,t)=>s+t.actual,0);const completed=day.blocks.filter(b=>b.done).length;
 async function commit(nextData:Snapshot,notice="已保存"){
  if(lock.current||loading)return false;lock.current=true;setBusy(true);setError('');setUndo(null);
  try{
   const changes:Record<string,Day>={};for(const [d,value] of Object.entries(nextData.days))if(JSON.stringify(value)!==JSON.stringify(data.days[d]))changes[d]=value;
   const r=await fetch('/api/planner',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({date,revision:data.revision,active:nextData.active,days:changes})});
   const result=await r.json();if(!r.ok){if(result.snapshot)setData(result.snapshot);throw new Error(result.error)}
   setData(result.snapshot??{...nextData,revision:result.revision});setMessage(notice);return true;
  }catch(e){setError((e as Error).message);return false}finally{lock.current=false;setBusy(false)}
 }
 function changeDay(s:Snapshot,d=date){if(!s.days[d])s.days[d]=routine(s.settings??defaults);return s.days[d]}
 function stopTimer(s:Snapshot){if(!s.active)return;const a=s.active;const end=Date.now();if(end>a.startedAt)changeDay(s,a.day).logs.push({id:a.id,blockId:a.blockId,title:a.title,category:a.category,start:a.startedAt,end});s.active=null}
 async function start(b:Block,blockDate=date){if(blockDate!==clock(Date.now(),settings.wake).planDate)return;const s=clone(data);stopTimer(s);const d=changeDay(s,blockDate);d.blocks=d.blocks.map(x=>x.id===b.id?{...x,done:false}:x);s.active={id:crypto.randomUUID(),day:blockDate,blockId:b.id,title:b.title,category:b.category,startedAt:Date.now()};setSelected(b.id);await commit(s,"已开始计时，刷新页面也会保留")}
 async function pause(){const s=clone(data);stopTimer(s);return commit(s,"计时已暂停，这一段已记入实际用时")}
 async function finish(b:Block,blockDate=date){const s=clone(data);if(s.active?.blockId===b.id&&s.active.day===blockDate)stopTimer(s);const d=changeDay(s,blockDate);d.blocks=d.blocks.map(x=>x.id===b.id?{...x,done:!x.done}:x);if(await commit(s,b.done?"已取消完成标记":"已完成。实际用时以计时或补记为准")){setSelected('');setUndo({date:blockDate,id:b.id,done:b.done})}}
 async function saveFocus(payload:Record<string,unknown>):Promise<Snapshot>{
  if(lock.current||loading)throw new Error("正在同步，请稍候再试。");lock.current=true;setBusy(true);setError('');
  try{const r=await fetch('/api/focus',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({date,revision:data.revision,...payload})});const result=await r.json();if(!r.ok){if(result.snapshot)setData(result.snapshot);throw new Error(result.error)}setData(result.snapshot);setUndo(null);setOnline(true);return result.snapshot;}finally{lock.current=false;setBusy(false)}
 }
 function editNextStep(b:Block|undefined,d:string,paused=false){if(b)setMemoTarget({date:d,id:b.id,title:blockTitle(b),text:nextStepFor(data,b),paused})}
 async function saveNextStep(text:string){if(!memoTarget)return false;await saveFocus({action:'note',targetDate:memoTarget.date,blockId:memoTarget.id,text});setMessage("下一步已保存，回来时可以接着做");return true}
 function checkTimer(reason:ReviewTarget['reason']='manual'){if(active)setReviewTarget({active:{...active},at:Date.now(),reason})}
 async function pauseForUser(){if(reviewDue(active,Date.now())){checkTimer('pause');return}const b=activeBlock,d=active?.day;if(await pause()){if(b&&d){setSelected(d===date?b.id:'');editNextStep(b,d,true)}}}
 function recover(){if(active){checkTimer('recover');return}setFocusOpen(false);openPlan(time.planDate,'recover')}
 async function saveReview(review:TimerReview){
  const target=reviewTarget;if(!target)return false;const b=(data.days[target.active.day]??routine(settings)).blocks.find(b=>b.id===target.active.blockId);
  await saveFocus({action:'review',review});setMessage(review.resume?"已确认，计时继续":"核对已保存，计时已暂停");
  if(!review.resume){setSelected(target.active.day===date?target.active.blockId:'');if(target.reason==='recover'){setFocusOpen(false);openPlan(time.planDate,'recover')}else editNextStep(b,target.active.day,true)}
  return true;
 }
 async function undoCompletion(){if(!undo||!data.days[undo.date])return;const s=clone(data);changeDay(s,undo.date).blocks=changeDay(s,undo.date).blocks.map(b=>b.id===undo.id?{...b,done:undo.done}:b);await commit(s,"已撤销完成标记，实际记录保留")}
 function edit(b?:Block){if(b?.locked&&!b.taskId){setWorkspace('settings');return}if(b?.taskId){setWorkspace('backlog');return}setDeleteConfirm(false);setFormError('');setNewBlock(!b);setBlockDraft(b?{...b}:{id:crypto.randomUUID(),title:'',category:'life',start:1215,end:1245,note:'',done:false})}
 function addInGap(range:TimeRange){if(busy||loading)return;const draft=draftInGap(day,range);if(!draft){setError('这段空档已经变化，请重新选择。');return}setDeleteConfirm(false);setFormError('');setNewBlock(true);setBlockDraft(draft)}
 async function saveBlock(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!blockDraft)return;const f=new FormData(e.currentTarget);const {start,end}=editedBlockTimes(blockDraft,String(f.get('start')),String(f.get('end')),settings.wake);const b={...blockDraft,start,end};const s=clone(data);const d=changeDay(s);d.mode='custom';d.blocks=(newBlock?[...d.blocks,b]:d.blocks.map(x=>x.id===b.id?b:x)).sort((a,b)=>a.start-b.start);const valid=daySchema.safeParse(d);if(!valid.success){setFormError(valid.error.issues[0].message);return}if(await commit(s,"时间块已更新"))setBlockDraft(null)}
 async function removeBlock(){if(!blockDraft)return;const s=clone(data);const d=changeDay(s);d.blocks=d.blocks.filter(b=>b.id!==blockDraft.id);d.mode='custom';if(await commit(s,"已删除计划，实际记录仍保留"))setBlockDraft(null)}
 function record(b?:Block,log?:Log){setFormError('');setDeleteConfirm(false);const base=b??focus;const fallback=localEpoch(date,base?.start??450);const st=log?.start??Math.min(fallback,Date.now()-5*60000);const en=log?.end??Math.max(st+60000,Math.min(localEpoch(date,base?.end??480),Date.now()));setLogDraft({id:log?.id??crypto.randomUUID(),blockId:log?.blockId??base?.id??'',title:log?.title??base?.title??"实际活动",category:log?.category??base?.category??'life',start:localInput(st),end:localInput(en)})}
 async function saveLog(e:React.FormEvent){e.preventDefault();if(!logDraft)return;try{const original=day.logs.find(l=>l.id===logDraft.id);const l:Log={...logDraft,start:original&&localInput(original.start)===logDraft.start?original.start:parseLocalInput(logDraft.start),end:original&&localInput(original.end)===logDraft.end?original.end:parseLocalInput(logDraft.end)};if(clock(l.start,settings.wake).planDate!==date)throw new Error("开始时间需属于选中的作息日");if(l.end>Date.now())throw new Error("实际结束时间不能晚于现在");const s=clone(data);const d=changeDay(s);d.logs=[...d.logs.filter(x=>x.id!==l.id),l].sort((a,b)=>a.start-b.start);const v=daySchema.safeParse(d);if(!v.success)throw new Error(v.error.issues[0].message);if(await commit(s,"实际用时已保存"))setLogDraft(null)}catch(e){setFormError((e as Error).message)}}
 async function deleteLog(){if(!logDraft)return;const s=clone(data);changeDay(s).logs=changeDay(s).logs.filter(l=>l.id!==logDraft.id);if(await commit(s,"这条实际记录已删除"))setLogDraft(null)}
 async function applyTemplate(){const s=clone(data);const old=changeDay(s);s.days[date]={...template(mode),goal:old.goal,logs:old.logs};if(await commit(s,"当天计划已更换，实际记录已保留"))setTemplateOpen(false)}
 async function savePlanning(payload:Record<string,unknown>):Promise<Snapshot|null>{
  if(lock.current||loading)throw new Error("正在保存，请稍候再试。");lock.current=true;setBusy(true);
  try{const r=await fetch('/api/planning',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({date,revision:data.revision,...payload})});const result=await r.json();if(!r.ok){if(result.snapshot)setData(result.snapshot);throw new Error(result.error)}setData(result.snapshot);setGoal((result.snapshot.days[date]??routine(result.snapshot.settings??defaults)).goal);setError('');setSelected('');if(!payload.quiet){setUndo(null);setMessage(payload.action==='apply'?"日程已确认并保存":payload.action==='capture'?"已整理并保存，请确认任务":payload.action==='settings'?"作息设置已保存，新草稿会使用这些时间":"已保存")}return result.snapshot;}finally{lock.current=false;setBusy(false)}
 }
 function openPlan(d:string,nextIntent:ReplanIntent=null){if(d!==date)setLoading(true);setIntent(nextIntent);setDate(d);if(view==='review')setView('overview');setWorkspace('plan')}
 function navigate(d:string){if(!busy){if(d!==date)setLoading(true);setDate(d);setUndo(null);setSelected('');setBlockDraft(null);setLogDraft(null);setError('')}}
 function scrollNow(){setView('today');setAgendaOpen(true);setSelected(current?.id??'');setTimeout(()=>document.getElementById('block-'+current?.id)?.scrollIntoView({behavior:'smooth',block:'center'}),50)}
 const refreshRef=useRef<()=>void>(()=>{}),refreshInFlight=useRef(false);
 const syncGate=useRef({revision:0,date:'',blocked:true});
 syncGate.current={revision:data.revision,date,blocked:loading||!!workspace||!!blockDraft||!!logDraft||!!memoTarget||!!reviewTarget||goal!==day.goal};
 refreshRef.current=()=>{
  if(!date||lock.current||syncGate.current.blocked||refreshInFlight.current||document.visibilityState!=='visible')return;
  const requestId=loadId.current,revision=data.revision;refreshInFlight.current=true;setSyncing(true);
  void fetch('/api/planner?date='+date,{cache:'no-store'}).then(async r=>{const state=await r.json();if(!r.ok)throw new Error(state.error);const gate=syncGate.current;if(requestId!==loadId.current||lock.current||gate.blocked||gate.date!==date||gate.revision!==revision)return;setData(state);setGoal((state.days[date]??routine(state.settings??defaults)).goal);if(state.revision!==revision)setUndo(null);setOnline(true)}).catch(()=>setOnline(false)).finally(()=>{refreshInFlight.current=false;setSyncing(false)});
 };
 useEffect(()=>{const refresh=()=>refreshRef.current();const offline=()=>setOnline(false);const reconnect=()=>{setOnline(true);refresh()};setOnline(navigator.onLine);window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);window.addEventListener('online',reconnect);window.addEventListener('offline',offline);const timer=setInterval(refresh,30000);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh);window.removeEventListener('online',reconnect);window.removeEventListener('offline',offline)}},[]);
 function jump(section:'now'|'agenda'|'review'|'overview'){setView(section==='review'?'review':section==='overview'?'overview':'today');if(section==='agenda')setAgendaOpen(true);setTimeout(()=>{const el=document.getElementById(section==='now'?'now-panel':section==='overview'?'overview-current':'day-workspace');el?.scrollIntoView({behavior:'smooth',block:'start'});el?.focus({preventScroll:true})},60)}
 function exportRecords(){const rows=[[tr("日期"),tr("活动"),tr("分类"),tr("开始（多伦多）"),tr("结束（多伦多）"),tr("分钟")],...day.logs.map(l=>[date,recordTitle(l),categories[l.category].label,new Date(l.start).toLocaleString(locale,{timeZone:'America/Toronto'}),new Date(l.end).toLocaleString(locale,{timeZone:'America/Toronto'}),((l.end-l.start)/60000).toFixed(1)])];const csv='\uFEFF'+rows.map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`alex-${date}.csv`;a.click();URL.revokeObjectURL(url)}
 return <div className={'app-shell '+(view==='review'?'review-mode':view==='overview'?'overview-mode':'today-mode')}>
  <aside className="sidebar">
   <a className="brand" href="/" aria-label={tr("留白首页")}><span className="brand-symbol"><Leaf size={23}/></span><span>{locale==='zh-CN'?tr("留白"):"Alex Rhythm"}<small>A LITTLE ROOM</small></span></a>
   <div className="workspace-label">{tr("我的空间")}</div>
   <button className={'nav-item '+(view!=='review'?'active':'')} aria-label={tr("我的一天")} onClick={()=>setView('overview')}><CalendarDays size={19}/>{tr("我的一天")}<span className="nav-dot"/></button>
   <button className={'nav-item '+(view==='review'?'active':'')} aria-label={tr("时间回顾")} onClick={()=>setView('review')}><TrendingUp size={19}/>{tr("时间回顾")}</button>
   <button className="nav-item" disabled={busy||loading} aria-label={tr("专注空间")} onClick={openFocus}><Focus size={19}/>{tr("专注空间")}</button>
   <button className="nav-item" disabled={busy||loading} aria-label={tr("待办池")} onClick={()=>setWorkspace('backlog')}><Inbox size={19}/>{tr("待办池")}</button><button className="nav-item" disabled={busy||loading} aria-label={tr("固定作息")} onClick={()=>setWorkspace('settings')}><Settings2 size={19}/>{tr("固定作息")}</button><div className="side-note"><div className="orbit"><Sun size={25}/></div><strong>{tr("给每一天，一点留白。")}</strong><p>{tr("计划是帮手。")}<br/>{tr("偶尔偏离，也可以从现在继续。")}</p></div>
   <div className="profile"><span className="avatar">A</span><div><strong>Alex</strong><small>America/Toronto</small></div><span className="profile-dot"/></div>
  </aside>
  <main className="main-shell">
   <header className="topbar"><span className="breadcrumb">{tr("我的空间 ")}<ChevronRight size={14}/> {view==='overview'?tr("一日总览"):view==='today'?tr("详细日程"):tr("时间回顾")}</span><div className="topbar-actions header-controls"><LanguagePicker/><span className="sync-state" role="status" aria-atomic="true"><span className="sync-indicator" aria-hidden="true">{busy?<Loader2 size={14} className="spin"/>:<span className="status-dot"/>}</span><span>{!online?tr("连接中断"):busy?tr("正在保存"):loading?tr("正在载入"):syncing?tr("正在同步"):tr("已连接 · 私人日程")}</span></span></div></header>
   <div className="page-wrap">
    <div className="page-heading"><div><p className="eyebrow">{tr("Alex 的一天")}</p><h1>{view==='overview'?tr("一眼看清这一天"):view==='today'?tr("详细日程"):tr("时间回顾")}</h1></div><div className="date-nav"><Button variant="ghost" size="icon" aria-label={tr("前一天")} disabled={busy||loading} onClick={()=>navigate(shiftDate(date,-1))}><ChevronLeft/></Button><label className="date-picker"><CalendarDays size={17}/><input aria-label={tr("选择日期")} type="date" value={date} disabled={busy||loading} onChange={e=>e.target.value&&navigate(e.target.value)}/></label><Button variant="ghost" size="icon" aria-label={tr("后一天")} disabled={busy||loading} onClick={()=>navigate(shiftDate(date,1))}><ChevronRight/></Button><Button variant="outline" disabled={busy||loading} onClick={()=>navigate(time.planDate)}>{tr("今天")}</Button></div></div>
    {!online&&<div className="error-banner" role="status">{tr("暂时无法同步。恢复连接后会重试；保存失败时请保留页面。")}</div>}
    {error&&<div className="error-banner" role="alert"><span>{tr(error)}</span><Button variant="outline" size="sm" onClick={()=>load(date)} disabled={busy}>{tr("重新载入")}</Button></div>}
    {message&&<div className="save-message" role="status"><Check size={16}/><span>{tr(message)}</span>{undo&&<Button variant="ghost" disabled={busy} onClick={undoCompletion}>{tr("撤销")}</Button>}</div>}
    {loading?<div className="loading-panel"><Loader2 className="spin"/>{tr("正在打开你的一天…")}</div>:<div className="content-grid">
     <div className="primary-column" id="day-workspace" tabIndex={-1}>
      {view!=='review'&&<section className="planning-entry"><div><span className="planning-entry-icon"><Sparkles size={21}/></span><div><strong>{data.draft?tr("接着上次的规划"):tr("给明天留一点方向")}</strong><p>{tr("晚间规划 · 早晨微调")}</p></div></div><div className="planning-entry-actions"><Button disabled={busy} onClick={()=>openPlan(data.draft&&date>=time.planDate?date:shiftDate(time.planDate,1))}>{data.draft&&date>=time.planDate?tr("继续规划"):tr("规划明天")}<ArrowRight size={16}/></Button><Button variant="outline" disabled={busy} onClick={()=>openPlan(time.planDate)}>{time.planMinute<600?tr("早晨微调"):tr("调整今天")}</Button><Button variant="ghost" disabled={busy} onClick={()=>setWorkspace('backlog')}><Inbox size={16}/>{tr("待办池 ")}{(data.tasks??[]).filter(t=>t.status==='todo').length}</Button></div></section>}

      <Tabs value={view} onValueChange={setView}>
       <div className="section-toolbar"><div className="view-tabs-viewport"><TabsList className="view-tabs" aria-label={tr("我的一天")}><TabsTrigger value="overview"><LayoutDashboard/>{tr("一日总览")}</TabsTrigger><TabsTrigger value="today"><CalendarDays/>{tr("详细日程")}</TabsTrigger><TabsTrigger value="review"><TrendingUp/>{tr("回顾")}</TabsTrigger></TabsList></div><span className="day-label">{date&&dateLabel(date)}</span></div>
       <TabsContent value="overview"><DayOverview onAddInGap={addInGap} day={day} date={date} settings={settings} active={active} now={now} minute={time.planMinute} isToday={isToday} busy={busy} current={overviewCurrent} nextStep={nextStepFor(data,active?activeBlock:overviewCurrent)} getNextStep={b=>nextStepFor(data,b)} onPause={pauseForUser} onRecover={recover} onReview={()=>checkTimer()} reviewDue={reviewDue(active,now)} onFocus={openFocus} onPlan={()=>openPlan(date)} canPlan={date>=time.planDate} onDetails={id=>{setView('today');setAgendaOpen(true);if(id)setSelected(id);setTimeout(()=>document.getElementById(id?'block-'+id:'day-workspace')?.scrollIntoView({behavior:'smooth',block:'start'}),60)}}/></TabsContent>
       <TabsContent value="today">
        <section className={"agenda-panel "+(agendaOpen?"agenda-expanded":"")}>
         <div className="agenda-heading"><div><h2>{tr("全天安排")}</h2><p>{completed}{tr(" 项已完成 · 点击任务查看或记录")}</p></div><Button variant="outline" size="sm" onClick={()=>openPlan(date)} disabled={busy||date<time.planDate}><SlidersHorizontal/>{tr("规划这一天")}</Button></div>
         <button className="agenda-toggle" aria-expanded={agendaOpen} aria-controls="agenda-body" onClick={()=>setAgendaOpen(!agendaOpen)}>{agendaOpen?tr("收起全天安排"):tr("展开全天安排")}<ArrowDown size={16}/></button><div className="agenda-body" id="agenda-body"><div className="agenda-tools"><span><i className="tiny-dot"/>{tr("计划时间 · 多伦多")}</span><div>{isToday&&current&&<Button variant="ghost" size="sm" onClick={scrollNow}><ArrowDown/>{tr("定位现在")}</Button>}<Button variant="ghost" size="sm" onClick={()=>edit()} disabled={busy}><Plus/>{tr("时间块")}</Button></div></div>
         <div className="agenda-list">{day.blocks.map(b=>{const Icon=icons[b.category],cat=categories[b.category];const logged=day.logs.filter(l=>l.blockId===b.id).reduce((s,l)=>s+(l.end-l.start)/60000,0)+(active?.day===date&&active.blockId===b.id?(now-active.startedAt)/60000:0);const isCurrent=current?.id===b.id;const running=active?.day===date&&active.blockId===b.id;return <div key={b.id} id={'block-'+b.id} className={'agenda-row '+(focus?.id===b.id?'selected ':'')+(b.done?'done ':'')+(isCurrent?'current ':'')} style={{'--cat':cat.color,'--pale':cat.pale} as CSSProperties}>
          <div className="time-gutter"><strong>{hm(b.start)}</strong><span>{b.end>1440?tr("次日 "):''}{hm(b.end)}</span></div>
          <div className="timeline-track"><button aria-label={b.done?tr("取消完成 ")+blockTitle(b):tr("完成 ")+blockTitle(b)} className={'complete-button '+(b.done?'checked':'')} disabled={busy} onClick={()=>finish(b)}>{b.done?<Check size={12}/>:<span/>}</button></div>
          <button className="block-body" onClick={()=>{setSelected(b.id);if(window.matchMedia('(max-width:760px)').matches)jump('now')}}><div className="block-title"><Icon size={16}/><strong>{blockTitle(b)}</strong>{running?<span className="live-label">{tr("计时中")}</span>:isCurrent?<span className="now-label">{tr("现在")}</span>:null}</div><div className="block-meta"><span>{categories[b.category].label}</span><span>·</span><span>{duration(b.end-b.start)}</span>{logged>0&&<span className="logged-meta">{tr("已记 ")}{duration(logged)}</span>}</div></button>
          <Button className="edit-block" variant="ghost" size="icon-sm" aria-label={tr("编辑 ")+blockTitle(b)} onClick={()=>edit(b)} disabled={busy}><Pencil size={14}/></Button>
         </div>})}</div>
         <button className="add-block" onClick={()=>edit()} disabled={busy}><Plus size={17}/>{tr("留一个新的时间块")}</button>
         <div className="agenda-footnote"><Leaf size={14}/>{tr("实际用时只累计已计时或补记的部分。")}</div></div>
        </section>
       </TabsContent>
       <TabsContent value="review"><div className="stat-grid"><Stat icon={<LayoutDashboard/>} label={tr("工作时间")} value={duration(work.planned)} detail={tr("已记录 ")+duration(work.actual)} color="work"/><Stat icon={<Dumbbell/>} label={tr("健身房时间窗")} value={duration(summary.find(s=>s.cat==='move')!.planned)} detail={tr("包含往返、准备与洗澡")} color="move"/><Stat icon={<Cat/>} label={tr("陪猫玩")} value={duration(catMinutes)} detail={tr("白天一轮 · 晚上一轮")} color="cat"/><Stat icon={<BookOpen/>} label={tr("睡眠窗口")} value={duration(sleep)} detail={tr("睡前留一点时间读书")} color="rest"/></div><section className="review-panel"><div className="panel-heading"><div><h2>{tr("计划与实际")}</h2><p>{tr("已记录 ")}{duration(actualTotal)}{tr("。跨日记录归入开始日。")}</p></div><div className="chart-legend"><span><i className="planned-key"/>{tr("计划")}</span><span><i/>{tr("实际")}</span></div></div>
        <div className="comparison-chart">{summary.map(t=>{const max=Math.max(60,...summary.map(s=>Math.max(s.planned,s.actual)));return <div className="comparison-row" key={t.cat}><div className="comparison-label"><span>{tr(t.label)}</span><small>{tr("计划 ")}{duration(t.planned)}{tr(" / 实际 ")}{duration(t.actual)}</small></div><div className="bar-track"><div className="bar planned" style={{width:100*t.planned/max+'%',background:t.color}}/></div><div className="bar-track"><div className="bar" style={{width:100*t.actual/max+'%',background:t.color}}/></div></div>})}</div>
        {!day.logs.length&&!active&&<p className="empty-hint">{tr("第一次计时或补记后，这里就会出现实际用时。")}</p>}
       </section><section className="review-panel"><div className="panel-heading"><div><h2>{tr("最近 7 天 · 实际工作")}</h2><p>{tr("只展示已记录的数据，不用追求每天一样多。")}</p></div></div><div className="week-chart">{Array.from({length:7},(_,i)=>shiftDate(date,i-6)).map(d=>{const t=totals(data.days[d]??{...template(),blocks:[]},active,d,now).find(s=>s.cat==='work')!;return <div key={d} className="week-column"><span>{t.actual?duration(t.actual):'—'}</span><div className="week-track"><div style={{height:Math.min(100,t.actual/weekMax*100)+'%'}}/></div><small>{d.slice(5).replace('-','/')}</small></div>})}</div></section>
       <section className="review-panel"><div className="panel-heading"><div><h2>{tr("实际记录 ")}<span className="count">{day.logs.length}</span></h2><p>{tr("忘了开计时？随时补记，也可以修正。")}</p></div><div className="record-actions"><Button variant="ghost" size="sm" onClick={exportRecords} disabled={!day.logs.length}>{tr("导出 CSV")}</Button><Button variant="outline" size="sm" onClick={()=>record()} disabled={busy}><Plus/>{tr("补记")}</Button></div></div>{day.logs.length?<div className="logs-list">{[...day.logs].sort((a,b)=>b.start-a.start).map(l=><button className="log-row" key={l.id} onClick={()=>record(undefined,l)}><i style={{background:categories[l.category].color}}/><span><strong>{recordTitle(l)}</strong><small>{new Date(l.start).toLocaleTimeString(locale,{timeZone:'America/Toronto',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'})}–{new Date(l.end).toLocaleTimeString(locale,{timeZone:'America/Toronto',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'})}</small></span><b>{duration((l.end-l.start)/60000)}</b><Pencil size={14}/></button>)}</div>:<div className="empty-record"><Clock3 size={28}/><strong>{tr("你的第一段时间，准备好被看见。")}</strong><span>{tr("从计时开始，或补记已经做过的事。")}</span></div>}</section></TabsContent>
      </Tabs>
     </div>
     <aside className="right-column">
      <NowPanel nextStep={nextStepFor(data,shownBlock)} canNote={!!shownBlock} onNote={()=>editNextStep(shownBlock,shownDate)} reviewDue={reviewDue(active,now)} onReview={()=>checkTimer()} onRecover={recover} onFocus={openFocus} focus={focus} next={next} active={active} now={now} date={date} isToday={isToday} busy={busy} goal={day.goal} canFinish={active?.day===date&&day.blocks.some(b=>b.id===active.blockId)} onStart={start} onPause={pauseForUser} onFinish={()=>{const b=active?day.blocks.find(b=>b.id===active.blockId):focus;if(b)void finish(b)}} onRecord={()=>record(active?.day===date?day.blocks.find(b=>b.id===active.blockId):focus)} onPlan={i=>openPlan(time.planDate,i)} onToday={()=>navigate(time.planDate)}/>
      <details className="day-extras"><summary><Settings2 size={16}/><span>{tr("今日重点与固定作息")}</span></summary>
      <section className="goal-card"><div className="small-heading"><Sparkles size={17}/><h3>{tr("今天最重要的一件事")}</h3></div><Textarea value={goal} onChange={e=>setGoal(e.target.value)} placeholder={tr("写一个能开始的小动作…")} maxLength={240} aria-label={tr("今天最重要的一件事")}/><div className="goal-footer"><span>{tr("只写一件就够了。")}</span><Button variant="ghost" size="sm" disabled={busy||goal===day.goal} onClick={()=>{const s=clone(data);changeDay(s).goal=goal;void commit(s)}}><Save size={14}/>{tr("保存")}</Button></div></section>
      <section className="anchors-card"><h3>{tr("固定作息 · 自动排程会保留")}</h3><div><span>{hm(settings.wake)}</span>{tr("起床")}</div><div><span>{hm(settings.breakfast)}</span>{tr("早餐")}</div><div><span>{hm(settings.lunch)}</span>{tr("午餐")}</div><div><span>{hm(settings.dinner)}</span>{tr("晚餐")}</div><div><span>{hm(settings.bed)}</span>{tr("睡觉")}</div><Button variant="ghost" size="sm" onClick={()=>setWorkspace('settings')}><Settings2 size={14}/>{tr("调整固定作息")}</Button></section>
      </details>
     </aside>
    </div>}
    <footer className="page-footer"><span>{tr("留白 · 为真实生活留一点空间")}</span><span>{tr("America/Toronto · 每天 ")}{hm(settings.wake)}{tr(" 开始一个作息日")}</span></footer>
   </div>
  </main>
  <nav className="mobile-nav" aria-label={tr("主要操作")}><button aria-current={view==='overview'?'page':undefined} aria-label={tr("一日总览")} onClick={()=>jump('overview')}><LayoutDashboard/><span>{tr("总览")}</span></button><button aria-current={view==='today'?'page':undefined} onClick={()=>jump('agenda')}><CalendarDays/><span>{tr("详细")}</span></button><button disabled={busy||loading} onClick={()=>openPlan(shiftDate(time.planDate,1))}><Plus/><span>{tr("规划")}</span></button><button aria-current={view==='review'?'page':undefined} onClick={()=>jump('review')}><TrendingUp/><span>{tr("回顾")}</span></button></nav>
  <FocusMode nextStep={nextStepFor(data,focused.block)} onNote={()=>editNextStep(focused.block,focused.date)} reviewDue={reviewDue(active,now)} onReview={()=>checkTimer()} onRecover={recover} open={focusOpen} title={active?recordTitle(active):blockTitle(focused.block)} scene={sceneForActivity(focused.activity)} block={focused.block} next={focusNext} date={focused.date} startedAt={active?.startedAt} savedMs={focused.savedMs} now={now} running={focused.running} done={focused.done} busy={busy} loading={loading} error={tr(error)} online={online} syncing={syncing} canStart={!!focused.block&&focused.date===time.planDate} canFinish={!!focused.block&&!focused.done} canUndo={undo?.id===focused.id&&undo?.date===focused.date} onUndo={undoCompletion} onClose={()=>setFocusOpen(false)} onStart={()=>focused.block&&void start(focused.block,focused.date)} onPause={pauseForUser} onFinish={()=>focused.block&&void finish(focused.block,focused.date)} onNext={chooseFocusNext} onChoose={chooseFocusTask} onRecord={()=>{setFocusOpen(false);if(focused.date===date)record(focused.block);else navigate(focused.date)}}/>
  <NextStepDialog target={memoTarget} busy={busy} onClose={()=>setMemoTarget(null)} onSave={saveNextStep}/>
  <TimerReviewDialog target={reviewTarget} busy={busy} onClose={()=>setReviewTarget(null)} onSave={saveReview}/>
  <PlanningWorkspace intent={intent} mode={workspace} date={date} data={data} day={day} busy={busy} loading={loading} now={now} onClose={()=>setWorkspace(null)} onSave={savePlanning} onPause={pause}/>
  <Dialog open={!!blockDraft} onOpenChange={o=>!busy&&!o&&setBlockDraft(null)}><DialogContent className="editor-dialog"><DialogHeader><DialogTitle>{newBlock?tr("新的时间块"):tr("调整时间块")}</DialogTitle><DialogDescription>{tr("只修改这一日。相邻时间块有重叠时，会提示你调整。")}</DialogDescription></DialogHeader>{blockDraft&&<form onSubmit={saveBlock} className="editor-form"><Field label={tr("做什么")}><Input required maxLength={80} value={blockTitle(blockDraft)} onChange={e=>setBlockDraft({...blockDraft,title:e.target.value})}/></Field><div className="form-columns"><Field label={tr("开始时间")}><Input name="start" type="time" required defaultValue={hm(blockDraft.start)}/></Field><Field label={tr("结束时间")}><Input name="end" type="time" required defaultValue={hm(blockDraft.end)}/></Field></div><p className="form-note">{tr("作息日范围：")}{hm(settings.wake)}{tr(" 至次日 ")}{hm(settings.wake)}{tr("；凌晨时间计入次日。")}</p><Field label={tr("分类")}><NativeSelect value={blockDraft.category} onChange={e=>setBlockDraft({...blockDraft,category:e.target.value as Category})}>{Object.entries(categories).map(([key,c])=><option key={key} value={key}>{c.label}</option>)}</NativeSelect></Field><Field label={tr("给自己的提示")}><Textarea value={blockNote(blockDraft)} maxLength={500} onChange={e=>setBlockDraft({...blockDraft,note:e.target.value})}/></Field>{formError&&<p className="form-error" role="alert">{tr(formError)}</p>}{error&&<p className="form-error" role="alert">{tr(error)}</p>}<div className="dialog-actions">{!newBlock&&<Button type="button" variant="ghost" className="delete-button" disabled={busy||(active?.day===date&&active.blockId===blockDraft.id)} onClick={()=>deleteConfirm?removeBlock():setDeleteConfirm(true)}><Trash2 size={15}/>{deleteConfirm?tr("确认删除计划"):tr("删除")}</Button>}<Button type="submit" disabled={busy}>{busy?tr("保存中…"):tr("保存时间块")}</Button></div></form>}</DialogContent></Dialog>
  <Dialog open={!!logDraft} onOpenChange={o=>!busy&&!o&&setLogDraft(null)}><DialogContent className="editor-dialog"><DialogHeader><DialogTitle>{day.logs.some(l=>l.id===logDraft?.id)?tr("修正实际记录"):tr("补记实际用时")}</DialogTitle><DialogDescription>{date}{tr(" · 多伦多时间。记下真正做过的时间，短休可以分开记。")}</DialogDescription></DialogHeader>{logDraft&&<form className="editor-form" onSubmit={saveLog}><Field label={tr("做了什么")}><Input required maxLength={80} value={recordTitle(logDraft)} onChange={e=>setLogDraft({...logDraft,title:e.target.value})}/></Field><div className="form-columns"><Field label={tr("实际开始")}><Input type="datetime-local" required value={logDraft.start} onChange={e=>setLogDraft({...logDraft,start:e.target.value})}/></Field><Field label={tr("实际结束")}><Input type="datetime-local" required value={logDraft.end} onChange={e=>setLogDraft({...logDraft,end:e.target.value})}/></Field></div><p className="form-note">{tr("跨日计时归入开始时的作息日。记录之间不能重叠。")}</p><Field label={tr("分类")}><NativeSelect value={logDraft.category} onChange={e=>setLogDraft({...logDraft,category:e.target.value as Category})}>{Object.entries(categories).map(([key,c])=><option key={key} value={key}>{c.label}</option>)}</NativeSelect></Field>{formError&&<p className="form-error" role="alert">{tr(formError)}</p>}{error&&<p className="form-error" role="alert">{tr(error)}</p>}<div className="dialog-actions">{day.logs.some(l=>l.id===logDraft.id)&&<Button type="button" variant="ghost" className="delete-button" disabled={busy} onClick={()=>deleteConfirm?deleteLog():setDeleteConfirm(true)}><Trash2 size={15}/>{deleteConfirm?tr("确认删除记录"):tr("删除记录")}</Button>}<Button disabled={busy} type="submit">{busy?tr("保存中…"):tr("保存实际记录")}</Button></div></form>}</DialogContent></Dialog>
  <Dialog open={templateOpen} onOpenChange={o=>!busy&&setTemplateOpen(o)}><DialogContent className="editor-dialog"><DialogHeader><DialogTitle>{tr("给今天选一个节奏")}</DialogTitle><DialogDescription>{tr("替换当天计划与完成标记。已记录的实际用时和今日目标都会保留。")}</DialogDescription></DialogHeader><div className="template-options">{([{id:'normal',title:tr("日常节奏"),text:tr("7 小时工作时间块，晚饭与收拾 90 分钟。"),icon:Sun},{id:'shopping',title:tr("买菜日"),text:tr("晚餐用简餐，20:00–21:30 买菜与归置。"),icon:Coffee},{id:'slow',title:tr("慢慢做饭"),text:tr("给晚饭 2 小时，保留陪猫玩与睡前阅读。"),icon:Leaf}] as const).map(m=><button key={m.id} onClick={()=>setMode(m.id)} className={'template-option '+(mode===m.id?'chosen':'')}><m.icon size={21}/><span><strong>{m.title}</strong><small>{m.text}</small></span>{mode===m.id&&<Check size={18}/>}</button>)}</div>{active?.day===date&&<p className="form-note">{tr("先暂停当前计时，再更换当天模板。")}</p>}{error&&<p className="form-error">{tr(error)}</p>}<Button onClick={applyTemplate} disabled={busy||active?.day===date}><RotateCcw size={15}/>{tr("使用这个模板")}</Button></DialogContent></Dialog>
 </div>
}
function Stat({icon,label,value,detail,color}:{icon:React.ReactNode,label:string,value:string,detail:string,color:Category}){
 const {categories}=useLanguage();
return <div className="stat-card"><div className="stat-top"><span>{label}</span><span className="stat-icon" style={{color:categories[color].color,background:categories[color].pale}}>{icon}</span></div><strong>{value}</strong><small>{detail}</small></div>}
