'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,Clock3,Inbox,LockKeyhole,Pause,Pencil,Plus,Save,Sparkles,Sun,Trash2,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {NativeSelect} from '@/components/ui/native-select';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {categories,clock,duration,hm,type Block,type Category,type Day,type Snapshot} from '@/lib/planner';
import {defaults,freshDraft,settingsSchema,taskSchema,type PlanningDraft,type Settings,type Task} from '@/lib/planning';
import {planChanges} from '@/lib/planner-view';
import type {ReplanIntent} from './now-panel';
export type WorkspaceMode='plan'|'backlog'|'settings'|null;
type Props={mode:WorkspaceMode,intent:ReplanIntent,date:string,data:Snapshot,day:Day,busy:boolean,loading:boolean,now:number,onClose:()=>void,onSave:(payload:Record<string,unknown>)=>Promise<Snapshot|null>,onPause:()=>Promise<boolean>};
const numericTime=(text:string)=>{const [h,m]=text.split(':').map(Number);return h*60+m};
function draftPayload(d:PlanningDraft,ts:Task[]){return {input:d.input,selectedIds:d.selectedIds,tasks:ts.filter(t=>d.selectedIds.includes(t.id)&&t.status==='todo'),energy:d.energy,gym:d.gym,delay:d.delay??0,recoveryMinutes:d.recoveryMinutes??null,stage:d.stage==='preview'?'clarify':d.stage}}
function fingerprint(d:PlanningDraft,ts:Task[]){const p=draftPayload(d,ts);return JSON.stringify({...p,tasks:p.tasks.map(({createdAt,updatedAt,...t})=>t)})}
function ranges(blocks:Block[]){return [...blocks].sort((a,b)=>a.start-b.start).map(b=>`${hm(b.start)}–${b.end>=1440?'次日 ':''}${hm(b.end)}`).join('、')}
export default function PlanningWorkspace({mode,intent,date,data,day,busy,loading,now,onClose,onSave,onPause}:Props){
 const [recoverySetup,setRecoverySetup]=useState(false);
 const [draft,setDraft]=useState<PlanningDraft>(freshDraft()),[tasks,setTasks]=useState<Task[]>([]),[error,setError]=useState('');
 const [settings,setSettings]=useState<Settings>(defaults),[editing,setEditing]=useState<Task|null>(null),[reviewId,setReviewId]=useState<string|null>(null);
 const [saveStatus,setSaveStatus]=useState('已保存'),[autoSaving,setAutoSaving]=useState(false);
 const savedKey=useRef(''),failedKey=useRef(''),heading=useRef<HTMLHeadingElement>(null),localLock=useRef(false);
 useEffect(()=>{
  if(!mode||loading)return;
  const d=structuredClone(data.draft??freshDraft(data.settings??defaults)),ts=structuredClone(data.tasks??[]);
  savedKey.current=fingerprint(d,ts);failedKey.current='';
  if(mode==='plan'&&intent){
   d.stage=intent==='change'?'capture':'clarify';d.proposal=null;
   if(intent==='low')d.energy='low';if(intent==='delay')d.delay=15;
   if(intent==='recover'){
    d.delay=0;d.recoveryMinutes=d.recoveryMinutes??60;
    const ids=new Set([...d.selectedIds,...day.blocks.filter(b=>!b.done&&b.taskId).map(b=>b.taskId!)]);
    d.selectedIds=ts.filter(t=>t.status==='todo'&&ids.has(t.id)).map(t=>t.id);
   }
  }
  setRecoverySetup(mode==='plan'&&intent==='recover');setDraft(d);setTasks(ts);setSettings(data.settings??defaults);setError('');setEditing(null);setReviewId(null);setSaveStatus('已保存');
 },[mode,date,loading]);
 const selected=draft.selectedIds.flatMap(id=>tasks.find(t=>t.id===id&&t.status==='todo')??[]),missing=selected.filter(t=>!t.minutes);
 const today=date===clock(now||Date.now(),settings.wake).planDate,disabled=busy||loading,fieldsDisabled=loading||(busy&&!autoSaving);
 const inputKey=fingerprint(draft,tasks),dirty=inputKey!==savedKey.current;
 const inputPayload=()=>draftPayload(draft,tasks);
 async function save(payload:Record<string,unknown>,automatic=false){
  if(localLock.current)return false;localLock.current=true;const sentKey=inputKey;setError('');setSaveStatus('正在保存…');if(automatic)setAutoSaving(true);
  try{const r=await onSave({...payload,quiet:automatic});if(!r)return false;
   if(!automatic){const ts=structuredClone(r.tasks??[]);setTasks(ts);if(r.draft){setDraft(structuredClone(r.draft));savedKey.current=fingerprint(r.draft,ts)}}else savedKey.current=sentKey;
   failedKey.current='';setSaveStatus('已保存');return true;
  }catch(e){setError((e as Error).message);failedKey.current=sentKey;setSaveStatus('尚未保存');return false}finally{setAutoSaving(false);localLock.current=false}
 }
 useEffect(()=>{if(mode!=='plan'||loading||busy||draft.stage==='preview'||!dirty||failedKey.current===inputKey||!selected.every(t=>taskSchema.safeParse(t).success))return;const timer=setTimeout(()=>void save({action:'draft',...inputPayload()},true),1600);return()=>clearTimeout(timer)},[mode,loading,busy,inputKey]);
 useEffect(()=>{if(mode!=='plan'||draft.stage==='preview'||!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[mode,dirty,draft.stage]);
 const stage=draft.stage==='capture'?0:draft.stage==='clarify'?1:2,proposal=draft.proposal;
 const question=selected.find(t=>t.id===reviewId)??missing[0];
 useEffect(()=>{if(mode==='plan')heading.current?.focus({preventScroll:true})},[stage,question?.id,mode]);
 async function close(){if(disabled)return;if(mode==='plan'&&draft.stage!=='preview'&&dirty){if(!await save({action:'draft',...inputPayload()}))return}onClose()}
 function updateTask(t:Task){setTasks(ts=>ts.map(x=>x.id===t.id?t:x))}
 function choose(id:string,value:boolean){setDraft(d=>({...d,selectedIds:value?[...new Set([...d.selectedIds,id])]:d.selectedIds.filter(x=>x!==id)}));if(!value&&reviewId===id)setReviewId(null)}
 async function generate(){if(missing.length){setReviewId(missing[0].id);return}const bad=selected.map(t=>taskSchema.safeParse(t)).find(t=>!t.success);if(bad&&!bad.success){setError(bad.error.issues[0].message);return}await save({action:'generate',...inputPayload()})}
 async function saveSettings(){const valid=settingsSchema.safeParse(settings);if(!valid.success){setError(valid.error.issues[0].message);return}if(await save({action:'settings',settings}))onClose()}
 async function saveTask(){if(!editing)return;const p=taskSchema.safeParse(editing);if(!p.success){setError(p.error.issues[0].message);return}if(await save({action:'task',task:editing}))setEditing(null)}
 async function nextQuestion(){if(!question)return;const valid=taskSchema.safeParse(question);if(!valid.success||!question.minutes){setError('请填写任务名称，并选一个 5–600 分钟的预计时长。');return}if(await save({action:'draft',...inputPayload()}))setReviewId(missing.find(t=>t.id!==question.id)?.id??null)}
 function makePriority(id:string){setTasks(ts=>ts.map(t=>t.id===id?{...t,priority:1}:draft.selectedIds.includes(t.id)&&t.priority===1?{...t,priority:2}:t))}
 const changes=proposal?planChanges(day,proposal.day):[];
 const taskSummary=<div className="task-summary-list">{selected.map(t=><div className="task-summary" key={t.id}><button className="task-summary-text" disabled={disabled} onClick={()=>setReviewId(t.id)}><strong>{t.title}</strong><span>{t.minutes?duration(t.minutes):'待补充时长'}{t.fixedStart!==null?' · 固定 '+hm(t.fixedStart):''}</span></button><Button variant="ghost" aria-pressed={t.priority===1} className={t.priority===1?'priority-selected':''} disabled={disabled} onClick={()=>makePriority(t.id)}>{t.priority===1?<><Sparkles size={15}/>重点</>:'设为重点'}</Button><Button variant="ghost" size="icon" aria-label={'把 '+t.title+' 留在待办池'} disabled={disabled} onClick={()=>choose(t.id,false)}><X size={17}/></Button></div>)}</div>;
 return <Dialog open={mode!==null} onOpenChange={open=>!open&&void close()}><DialogContent showCloseButton={false} className={'planning-dialog v2-planning '+(mode==='settings'?'settings-dialog':'')}>
  <DialogHeader><DialogTitle>{mode==='settings'?'固定作息':mode==='backlog'?'待办池':recoverySetup?'从现在，重新接上':today?'调整今天':'规划这一天'}</DialogTitle><DialogDescription>{mode==='settings'?'生成日程时会保留这些时间。':mode==='backlog'?'每次规划，再决定继续哪些事。':`${date} · 多伦多时间 · 确认后才会修改日程`}</DialogDescription></DialogHeader>
  <Button className="workspace-close" variant="ghost" size="icon" aria-label={mode==='plan'?'保存草稿并关闭':'关闭'} disabled={disabled} onClick={close}><X/></Button>
  {loading?<div className="planning-loading">正在打开规划…</div>:<>
   {error&&<div className="planning-error" role="alert"><p>{error}</p>{mode==='plan'&&stage!==2&&<Button variant="outline" disabled={disabled} onClick={()=>save({action:'draft',...inputPayload()})}>检查后重试保存</Button>}</div>}
   {mode==='plan'&&<>
    {!recoverySetup&&<div className="planning-progress"><ol className="planning-steps" aria-label="规划进度">{['随手写','确认重点','确认安排'].map((label,i)=><li aria-current={i===stage?'step':undefined} className={i===stage?'current':i<stage?'passed':''} key={label}><span>{i<stage?<Check size={14}/>:i+1}</span>{label}</li>)}</ol><span className="draft-status" role="status">{saveStatus==='尚未保存'?saveStatus:busy?saveStatus:dirty&&stage!==2?'输入后自动保存':saveStatus}</span></div>}
    {recoverySetup&&<section className="recovery-setup"><h3 ref={heading} tabIndex={-1}>先给接下来留一点方向。</h3><label className="recovery-field"><span>今天还能给灵活任务留多久？</span><NativeSelect disabled={fieldsDisabled} value={draft.recoveryMinutes??60} onChange={e=>setDraft({...draft,recoveryMinutes:Number(e.target.value)})}>{[0,25,45,60,90,120,180,240,360,480].map(n=><option key={n} value={n}>{n?duration(n):'今天先不加任务'}</option>)}</NativeSelect><small>这是任务总用时；三餐、睡觉、健身和已有约会另外保留。</small></label><label className="recovery-field"><span>现在的精力怎么样？</span><NativeSelect disabled={fieldsDisabled} value={draft.energy} onChange={e=>setDraft({...draft,energy:e.target.value as PlanningDraft['energy']})}><option value="low">偏低 · 先做 25 分钟</option><option value="normal">还可以 · 每段 40 分钟</option><option value="high">充足 · 每段 50 分钟</option></NativeSelect></label>{selected.length>0?<label className="recovery-field"><span>优先接上哪件事？</span><NativeSelect disabled={fieldsDisabled} value={[...selected].sort((a,b)=>a.priority-b.priority)[0].id} onChange={e=>makePriority(e.target.value)}>{selected.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</NativeSelect></label>:<p className="recovery-help">今天还没有选中任务。可以从待办池选择，或写下一件想推进的事。</p>}<div className="protected-note"><LockKeyhole size={16}/><span>先看变化，再由你确认。排不下的事会留在待办池。</span></div><div className="planning-actions sticky-actions"><Button variant="outline" disabled={disabled} onClick={()=>{setRecoverySetup(false);setDraft({...draft,stage:'capture'})}}>选择或补充任务</Button><Button disabled={disabled} onClick={async()=>{setRecoverySetup(false);await generate()}}>看看接下来怎么安排<ArrowRight/></Button></div></section>}
    {!recoverySetup&&stage===0&&<div className="capture-flow"><section className="capture-main"><h3 ref={heading} tabIndex={-1} className="planning-question"><label htmlFor="brain-dump">{intent==='change'?'临时多了什么事？':'想把哪些事放进这一天？'}</label></h3><p className="planning-help">先随手写，不需要整理好再来。</p><Textarea id="brain-dump" className="brain-input" disabled={fieldsDisabled} value={draft.input} onChange={e=>setDraft({...draft,input:e.target.value})} maxLength={6000} placeholder="最重要的是完成网站原型，2 小时。下午 3 点开会，30 分钟。还要买菜，大约 1 小时。"/>
     <details className="input-hint"><summary>怎样写，更容易整理？</summary><p>一件事一句，写上预计多久，有约会就写具体时间。目前按标点、时长和时间规则整理；下一步可以逐项修改。</p></details></section>
     {tasks.some(t=>t.status==='todo')&&<details className="carry-panel"><summary><Inbox size={18}/>还有 {tasks.filter(t=>t.status==='todo').length} 件待办，这次要继续哪些？<span>已选 {draft.selectedIds.length}</span></summary><p>只安排你勾选的任务。</p><div className="carry-list">{tasks.filter(t=>t.status==='todo').sort((a,b)=>a.priority-b.priority).map(t=><label key={t.id} className="carry-item"><Checkbox disabled={disabled} checked={draft.selectedIds.includes(t.id)} onCheckedChange={v=>choose(t.id,v===true)}/><span><strong>{t.title}</strong><small>{t.minutes?duration(t.minutes):'时间待确认'}</small></span></label>)}</div></details>}
     <div className="planning-actions sticky-actions"><Button variant="ghost" disabled={disabled} onClick={close}>保存，稍后继续</Button><Button disabled={disabled} onClick={()=>draft.input.trim()?save({action:'capture',...inputPayload()}):save({action:'draft',...inputPayload(),stage:'clarify'})}>{draft.input.trim()?'整理并继续':draft.selectedIds.length?'继续':'只安排日常作息'}<ArrowRight/></Button></div>
    </div>}
    {!recoverySetup&&stage===1&&<>
     {question?<section className="question-card"><p className="question-count">{missing.length?`还需补充 ${missing.length} 件事的时长`:'调整这一件事'}</p><h3 ref={heading} tabIndex={-1}>这件事，这次准备投入多久？</h3><TaskFields task={question} disabled={fieldsDisabled} compact onChange={t=>{setReviewId(t.id);updateTask(t)}}/><div className="planning-actions"><Button variant="ghost" disabled={disabled} onClick={()=>choose(question.id,false)}>这次先不安排</Button><Button disabled={disabled||!question.minutes} onClick={nextQuestion}>记下，继续<ArrowRight/></Button></div></section>:<>
      <div className="clarify-heading"><div><h3 ref={heading} tabIndex={-1}>{selected.length?'哪一件最值得先推进？':'这一天，给自己什么节奏？'}</h3><p>{selected.length?'点任务可以修改；没选中的事仍留在待办池。':'先保留生活作息，也可以回去补充任务。'}</p></div></div>
      {taskSummary}
      {draft.recoveryMinutes!=null&&<div className="recovery-budget-note"><span>这次给灵活任务留出 {duration(draft.recoveryMinutes)}</span><Button variant="ghost" disabled={disabled} onClick={()=>setRecoverySetup(true)}>修改</Button><Button variant="ghost" disabled={disabled} onClick={()=>setDraft({...draft,recoveryMinutes:null})}>取消时间上限</Button></div>}
      <div className="day-context"><label><span><Sun size={17}/>预计精力</span><NativeSelect disabled={fieldsDisabled} value={draft.energy} onChange={e=>setDraft({...draft,energy:e.target.value as PlanningDraft['energy']})}><option value="low">偏低 · 工作 25 分钟一段</option><option value="normal">正常 · 工作 40 分钟一段</option><option value="high">充足 · 工作 50 分钟一段</option></NativeSelect></label><label><span>健身房 · 包含往返和洗澡</span><NativeSelect disabled={fieldsDisabled} value={draft.gym} onChange={e=>setDraft({...draft,gym:Number(e.target.value)})}>{[...new Set([0,30,60,90,120,150,180,settings.gym,draft.gym])].sort((a,b)=>a-b).map(v=><option key={v} value={v}>{v?duration(v):'这一天不安排'}</option>)}</NativeSelect></label></div>
      {today&&<label className="delay-choice"><span><Clock3 size={16}/>留多久再开始剩余任务？</span><NativeSelect disabled={fieldsDisabled} value={draft.delay??0} onChange={e=>setDraft({...draft,delay:Number(e.target.value)})}>{[0,15,30,60,90,120].map(n=><option key={n} value={n}>{n?n+' 分钟后':'从现在继续'}</option>)}</NativeSelect></label>}
      <div className="protected-note"><LockKeyhole size={16}/><span>三餐、起床和睡觉时间会保留。</span></div>
     </>}
     <div className="planning-actions sticky-actions"><Button variant="outline" disabled={disabled} onClick={()=>{setDraft({...draft,stage:'capture'});setReviewId(null)}}><ArrowLeft/>返回随手写</Button>{!question&&<Button disabled={disabled} onClick={generate}>看看怎么安排<ArrowRight/></Button>}</div>
    </>}
    {!recoverySetup&&stage===2&&proposal&&<>
     <div className="preview-heading"><div><h3 ref={heading} tabIndex={-1}>{changes.length?`有 ${changes.length} 项安排需要你确认`:'安排已经对齐了'}</h3><p>先看变化，完整日程可以展开。</p></div><Button variant="outline" disabled={disabled} onClick={()=>setDraft({...draft,stage:'clarify'})}><ArrowLeft/>返回调整</Button></div>
     {draft.recoveryMinutes!=null&&<p className="recovery-help">这次最多再安排 {duration(draft.recoveryMinutes)} 灵活任务；固定作息和约会保留。</p>}
     <div className="proposal-stats"><span><strong>{duration(proposal.day.blocks.filter(b=>b.category==='work').reduce((s,b)=>s+b.end-b.start,0))}</strong>计划工作</span><span><strong>{selected.length}</strong>选中任务</span><span><strong>{proposal.unplaced.length}</strong>暂未排入</span></div>
     <div className="protected-note"><LockKeyhole size={16}/><span>三餐、起床与睡觉受保护；已记录的时间保留。</span></div>
     {!!proposal.conflicts.length&&<div className="planning-error"><strong>请先调整这些时间冲突</strong>{proposal.conflicts.map((t,i)=><p key={i}>{t}</p>)}</div>}
     {(proposal.unplaced.length>0||proposal.warnings.length>0)&&<div className="proposal-notes">{proposal.unplaced.map(t=><p key={t.id}><strong>{t.title}</strong><br/>{t.reason}</p>)}{proposal.warnings.map((t,i)=><p key={i}>{t}</p>)}</div>}
     <div className="change-list">{changes.map(c=><article key={c.key} className={'change-row '+c.kind}><span className="change-kind">{c.kind==='new'?'新增':c.kind==='removed'?'暂不安排':'时间调整'}</span><div><strong>{c.title}</strong>{c.before.length>0&&<p><span>原来</span>{ranges(c.before)}</p>}{c.after.length>0?<p><span>现在</span>{ranges(c.after)}</p>:<p>{c.key.startsWith('task:')?'任务仍在待办池。':'不再占用这一天的时间。'}</p>}</div></article>)}</div>
     <details className="full-proposal"><summary>查看完整日程 · {proposal.day.blocks.length} 个时间块</summary><div className="proposal-list">{proposal.day.blocks.map(b=><div className="proposal-row" key={b.id}><span className="proposal-time">{hm(b.start)}–{b.end>=1440?'次日 ':''}{hm(b.end)}</span><i style={{background:categories[b.category].color}}/><span className="proposal-title">{b.title}{b.locked&&<LockKeyhole size={14} aria-label="固定时间"/>}</span>{b.done&&<small>已完成</small>}</div>)}</div></details>
     <div className="planning-actions sticky-actions">{data.active?.day===date?<Button variant="outline" onClick={async()=>{if(!await onPause())setError('暂停计时未保存，请检查连接后重试。')}} disabled={disabled}><Pause/>先暂停当前计时</Button>:<Button variant="outline" onClick={generate} disabled={disabled}>更新草稿</Button>}<Button disabled={disabled||proposal.conflicts.length>0||data.active?.day===date} onClick={async()=>{if(await save({action:'apply'}))onClose()}}><Check/>确认这个安排</Button></div>
    </>}
   </>}
  {mode==='settings'&&<><div className="settings-time-grid">{([{key:'wake',label:'起床'},{key:'breakfast',label:'早餐'},{key:'lunch',label:'午餐'},{key:'dinner',label:'晚餐'},{key:'bed',label:'睡觉'}] as const).map(item=><label className="setting-field" key={item.key}><span><LockKeyhole size={15}/>{item.label}</span><Input type="time" value={hm(settings[item.key])} onChange={e=>e.target.value&&setSettings({...settings,[item.key]:item.key==='bed'&&e.target.value==='00:00'?1440:numericTime(e.target.value)})}/></label>)}</div><p className="planning-help">三餐各预留 30 分钟。自动排程会保留这些时间。</p><div className="settings-other-grid"><label className="setting-field"><span>晚饭准备时间</span><NativeSelect value={settings.cook} onChange={e=>setSettings({...settings,cook:Number(e.target.value)})}>{[15,30,45,60,75,90].map(v=><option key={v} value={v}>{v} 分钟</option>)}</NativeSelect></label><label className="setting-field"><span>每日工作目标</span><NativeSelect value={settings.workGoal} onChange={e=>setSettings({...settings,workGoal:Number(e.target.value)})}>{[0,120,240,360,420,480].map(v=><option key={v} value={v}>{v?duration(v):'不设目标'}</option>)}</NativeSelect></label><label className="setting-field"><span>默认健身房时间窗</span><NativeSelect value={settings.gym} onChange={e=>setSettings({...settings,gym:Number(e.target.value)})}>{[0,30,60,90,120,150,180].map(v=><option key={v} value={v}>{v?duration(v):'当天再选'}</option>)}</NativeSelect></label><label className="setting-field"><span>每天预留缓冲</span><NativeSelect value={settings.buffer} onChange={e=>setSettings({...settings,buffer:Number(e.target.value)})}>{[15,30,45,60,90].map(v=><option key={v} value={v}>{v} 分钟</option>)}</NativeSelect></label></div><div className="settings-note"><strong>也会预留这些日常照顾</strong><p>陪猫玩两次，每次 15 分钟；睡前照顾猫咪、洗漱与阅读。健身房优先安排在午饭后，并预留往返时间。</p></div><Button onClick={saveSettings} disabled={disabled}><Save/>保存作息设置</Button></>}
  {mode==='backlog'&&<><div className="backlog-heading"><span>{tasks.filter(t=>t.status==='todo').length} 件待办 · 规划时再决定做哪些</span><Button disabled={disabled} onClick={()=>setEditing({id:crypto.randomUUID(),title:'',category:'work',minutes:null,priority:2,fixedStart:null,status:'todo',note:'',createdAt:Date.now(),updatedAt:Date.now()})}><Plus/>添加任务</Button></div>
   {editing&&<section className="backlog-editor"><TaskFields task={editing} onChange={setEditing} disabled={disabled}/><div className="planning-actions"><Button variant="ghost" disabled={disabled} onClick={()=>setEditing(null)}>取消编辑</Button><Button disabled={disabled} onClick={saveTask}><Save/>保存任务</Button></div></section>}
   {tasks.filter(t=>t.status!=='archived').length?<div className="backlog-list">{tasks.filter(t=>t.status!=='archived').sort((a,b)=>Number(a.status==='done')-Number(b.status==='done')||a.priority-b.priority).map(t=><div key={t.id} className={'backlog-row '+(t.status==='done'?'is-done':'')}><Checkbox aria-label={'完成任务 '+t.title} disabled={disabled} checked={t.status==='done'} onCheckedChange={v=>save({action:'task',task:{...t,status:v?'done':'todo'}})}/><button className="backlog-text" onClick={()=>setEditing({...t})}><strong>{t.title}</strong><small>{t.status==='done'?'已完成':t.priority===1?'最优先':t.priority===2?'希望推进':'有空再做'} · {t.minutes?duration(t.minutes):'时长待确认'}{t.fixedStart!==null?' · 固定 '+hm(t.fixedStart):''}</small></button><Button variant="ghost" size="icon" aria-label={'归档 '+t.title} disabled={disabled} onClick={()=>save({action:'task',task:{...t,status:'archived'}})}><Trash2 size={15}/></Button></div>)}</div>:<div className="backlog-empty"><Inbox size={28}/><p>还没有任务。可以先写下想到的一件事。</p></div>}
   {tasks.some(t=>t.status==='archived')&&<details className="archived-tasks"><summary>已归档 · {tasks.filter(t=>t.status==='archived').length}</summary>{tasks.filter(t=>t.status==='archived').map(t=><div key={t.id}><span>{t.title}</span><Button variant="ghost" size="sm" disabled={disabled} onClick={()=>save({action:'task',task:{...t,status:'todo'}})}>恢复到待办池</Button></div>)}</details>}
  </>}
  </>}
 </DialogContent></Dialog>
}
function TaskFields({task,onChange,disabled,compact=false}:{task:Task,onChange:(t:Task)=>void,disabled:boolean,compact?:boolean}){
 const extra=<><div className="task-detail-fields task-options"><label><span>优先级</span><NativeSelect disabled={disabled} value={task.priority} onChange={e=>onChange({...task,priority:Number(e.target.value)})}><option value="1">最优先</option><option value="2">希望推进</option><option value="3">有空再做</option></NativeSelect></label><label><span>分类</span><NativeSelect disabled={disabled} value={task.category} onChange={e=>onChange({...task,category:e.target.value as Category})}>{Object.entries(categories).map(([id,c])=><option key={id} value={id}>{c.label}</option>)}</NativeSelect></label></div><div className="fixed-task-field"><label><Checkbox disabled={disabled} checked={task.fixedStart!==null} onCheckedChange={v=>onChange({...task,fixedStart:v?900:null})}/>有固定开始时间（约会、会议）</label>{task.fixedStart!==null&&<Input aria-label="固定开始时间" type="time" disabled={disabled} value={hm(task.fixedStart)} onChange={e=>e.target.value&&onChange({...task,fixedStart:numericTime(e.target.value)})}/>}</div></>;
 return <div className="task-fields"><label className="task-title-field"><span>做什么</span><Input value={task.title} maxLength={160} disabled={disabled} onChange={e=>onChange({...task,title:e.target.value})} placeholder="一个可以开始的小动作"/></label><label className="task-duration"><span>本次预计投入</span><div className="duration-field"><Input aria-label="预计投入分钟" type="number" min={5} max={600} step={1} disabled={disabled} value={task.minutes??''} placeholder="选择下方时长，或自己填" onChange={e=>onChange({...task,minutes:e.target.value?Number(e.target.value):null})}/><span>分钟</span></div></label><div className="duration-shortcuts">{[15,30,60,90,120].map(v=><button key={v} disabled={disabled} aria-pressed={task.minutes===v} className={task.minutes===v?'selected':''} onClick={()=>onChange({...task,minutes:v})}>{v} 分</button>)}</div>{compact?<details className="task-advanced"><summary>优先级、分类与约会时间{task.fixedStart!==null?' · 固定 '+hm(task.fixedStart):''}</summary>{extra}</details>:extra}</div>
}
