import {categories as baseCategories, duration as chineseDuration, hm, template, type Block, type Log} from './planner';
import {fixedRoutine, routine} from './planning';
import {focusScenes as baseScenes} from './focus';
import type {OverviewGroup} from './day-overview';
import {messages} from './locales';

export const locales = ['zh-CN', 'en', 'es'] as const;
export type Locale = typeof locales[number];
export const LANGUAGE_KEY = 'alex-rhythm-language';
export const languageNames: Record<Locale, string> = {'zh-CN':'中文', en:'English', es:'Español'};
export function isLocale(value: unknown): value is Locale {return locales.includes(value as Locale)}
export function detectLocale(language: string): Locale {
 return language.toLowerCase().startsWith('es') ? 'es' : language.toLowerCase().startsWith('en') ? 'en' : 'zh-CN';
}
type Parameters = readonly (string | number | undefined | null)[];
const fill = (message: string, values: Parameters) => message.replace(/\{(\d+)\}/g, (match, index) => values[Number(index)] == null ? match : String(values[Number(index)]));
const escaped = (s:string) => s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
// Match only complete known server messages, never substrings of user-authored text.
const serverMessages = [
 '「{0}」{1} 与「{2}」冲突。',
 '「{0}」的固定时间已过去，或超出清醒时间。',
 '「{0}」还没有合适的空档，请调整时长或约会。',
 '这次先推进 {0}，其余 {1} 留在待办池，下次再决定。',
 '还需 {0}，剩余空档不足；保留在待办池。',
 '已排工作 {0}，你的目标是 {1}。可补充任务，也可以保留空档。',
 '「{0}」准备投入多久？请先选一个时长。',
];
const patterns = serverMessages.map(key=>({key, regex:new RegExp('^'+key.split(/\{\d+\}/).map(escaped).join('([\\s\\S]*?)')+'$')}));
export function translate(locale: Locale, key: string, values: Parameters = []): string {
 if(/^(Failed to fetch|NetworkError when attempting to fetch resource\.?|Load failed)$/.test(key))key='网络连接失败，请重试。';
 if(/^(String must contain|Number must be|Expected |Required$|Invalid enum value|Invalid input)/.test(key))key='请检查输入内容后重试。';
 const entry=messages[key];
 if(entry) return fill(locale==='zh-CN'?key:entry[locale==='en'?0:1],values);
 if(locale==='zh-CN')return fill(key,values);
 if(!values.length)for(const pattern of patterns){const match=key.match(pattern.regex);if(match)return translate(locale,pattern.key,match.slice(1).map(part=>localizeServerDuration(locale,part)))}
 return fill(key,values);
}
function localizeServerDuration(locale:Locale,value:string):string{
 const match=value.match(/^(\d+) 小时(?: (\d+) 分)?$|^(\d+) 分钟$/);
 return match?formatDuration(locale,match[3]?Number(match[3]):Number(match[1])*60+Number(match[2]??0)):value;
}
export function formatDuration(locale:Locale,minutes:number):string{
 const n=Math.max(0,Math.round(minutes));
 if(locale==='zh-CN')return chineseDuration(n);
 return n>=60?`${Math.floor(n/60)} h${n%60?` ${n%60} min`:''}`:`${n} min`;
}
// Identity + original field value is required before translating a built-in routine.
// Titles/notes edited by the user, even on a built-in block, remain verbatim.
const originals=new Map<string, {title:string,notes:Set<string>}>();
for(const block of [...template().blocks,...template('shopping').blocks,...template('slow').blocks,...fixedRoutine(),...routine().blocks]){
 const entry=originals.get(block.id)??{title:block.title,notes:new Set<string>()};entry.notes.add(block.note);originals.set(block.id,entry);
}
originals.get('routine-gym')?.notes.add('含往返、准备、训练和洗澡；按恢复情况调整。');
originals.set('routine-buffer',{title:'留白 · 休息或临时变化',notes:new Set([''])});
function original(block:{id:string,taskId?:string}){
 if(block.taskId)return undefined;
 return block.id.startsWith('routine-break-')?{title:'短休息',notes:new Set([''])}:originals.get(block.id);
}
export function localizedBlockTitle(locale:Locale,block:Pick<Block,'id'|'title'|'taskId'>|undefined):string{
 if(!block)return '';
 return original(block)?.title===block.title?translate(locale,block.title):block.title;
}
export function localizedBlockNote(locale:Locale,block:Block|undefined):string{
 if(!block)return '';
 return original(block)?.notes.has(block.note)?translate(locale,block.note):block.note;
}
export function localizedRecordTitle(locale:Locale,record:{blockId:string,title:string}|undefined):string{
 if(record?.blockId===''&&record.title==='休息（核对补记）')return translate(locale,record.title);
 return record?localizedBlockTitle(locale,{id:record.blockId,title:record.title}):'';
}
export function localizedGroupTitle(locale:Locale,group:OverviewGroup|undefined):string{
 if(!group)return '';
 if(!group.blocks.length)return translate(locale,group.title);
 if(group.blocks.every(b=>b.title===group.title))return localizedBlockTitle(locale,group.blocks[0]);
 // A group label is generated by the overview; its individual records stay untouched.
 return translate(locale,group.title);
}
export function localizedHelpers(locale:Locale){
 const tr=(key:string,values:Parameters=[])=>translate(locale,key,values);
 const timeLabel=(minute:number)=>(minute>=1440?tr('次日 '):'')+hm(minute);
 return {locale,tr,duration:(minutes:number)=>formatDuration(locale,minutes),
  categories:Object.fromEntries(Object.entries(baseCategories).map(([key,value])=>[key,{...value,label:tr(value.label)}])) as {[K in keyof typeof baseCategories]:Omit<typeof baseCategories[K],'label'>&{label:string}},
  focusScenes:Object.fromEntries(Object.entries(baseScenes).map(([key,value])=>[key,tr(value)])) as Record<keyof typeof baseScenes,string>,
  blockTitle:(block:Pick<Block,'id'|'title'|'taskId'>|undefined)=>localizedBlockTitle(locale,block),
  blockNote:(block:Block|undefined)=>localizedBlockNote(locale,block),
  recordTitle:(record:{blockId:string,title:string}|undefined)=>localizedRecordTitle(locale,record),
  groupTitle:(group:OverviewGroup|undefined)=>localizedGroupTitle(locale,group),
  dateLabel:(date:string)=>new Intl.DateTimeFormat(locale,{timeZone:'UTC',month:'long',day:'numeric',weekday:'long'}).format(new Date(date+'T12:00:00Z')),
  timeLabel,ranges:(blocks:Block[])=>[...blocks].sort((a,b)=>a.start-b.start).map(b=>`${timeLabel(b.start)}–${timeLabel(b.end)}`).join(', '),
 };
}
