import assert from 'node:assert/strict';
import {dayOverview,overviewGroups,overviewGroupAt} from '../../lib/day-overview';
import {template,daySchema,type Day} from '../../lib/planner';
import {defaults,routine} from '../../lib/planning';
import {draftInGap,editedBlockTimes} from '../../lib/block-editor';

const day=template(),before=JSON.stringify(day),periods=dayOverview(day,defaults);
assert.equal(periods.length,4);
assert.equal(periods.flatMap(p=>p.groups).reduce((n,g)=>n+g.end-g.start,0),1440);
for(const p of periods){assert.equal(p.groups[0].start,p.start);assert.equal(p.groups.at(-1)!.end,p.end);p.groups.forEach((g,i)=>{if(i)assert.equal(g.start,p.groups[i-1].end)})}
assert.equal(JSON.stringify(day),before);
const spanning:Day={mode:'custom',goal:'',logs:[],blocks:[{id:'long',title:'研究原型',category:'work',start:660,end:810,note:'保持原始记录',done:false}]};
const split=dayOverview(spanning,defaults).flatMap(p=>p.groups).filter(g=>g.blocks.some(b=>b.id==='long'));
assert.deepEqual(split.map(g=>[g.start,g.end]),[[660,720],[720,810]]);
assert.equal(split.reduce((n,g)=>n+g.end-g.start,0),150);assert.equal(split[1].blocks[0],spanning.blocks[0]);
assert.equal(overviewGroupAt(split[0],720),false);assert.equal(overviewGroupAt(split[1],720),true);
const meals:Day={...spanning,blocks:[{...spanning.blocks[0],id:'prep',title:'准备晚餐',category:'meal',start:1110,end:1155},{...spanning.blocks[0],id:'eat',title:'晚餐',category:'meal',start:1155,end:1185},{...spanning.blocks[0],id:'clean',title:'收拾',category:'meal',start:1185,end:1200}]};
const meal=overviewGroups(meals,1080,1380).find(g=>g.category==='meal')!;
assert.equal(meal.title,'晚餐与收拾');assert.equal(meal.blocks.length,3);assert.equal(meal.end-meal.start,90);
const twoTasks:Day={...spanning,blocks:[{...spanning.blocks[0],id:'a',taskId:'a',start:660,end:690},{...spanning.blocks[0],id:'b',taskId:'b',start:690,end:720}]};
assert.equal(overviewGroups(twoTasks,660,720).length,2);
const empty=dayOverview({...spanning,blocks:[]},defaults);
assert.ok(empty.every(p=>p.groups.length===1&&p.groups[0].category===null));
assert.equal(empty.flatMap(p=>p.groups).reduce((n,g)=>n+g.end-g.start,0),1440);
console.log('PASS: overview preserves full-day duration, gaps, source records, cross-period task identity, meal grouping, distinct tasks, and empty plans');

const routineDay=routine(defaults),routineBefore=JSON.stringify(routineDay);
const morningGap=dayOverview(routineDay,defaults)[0].groups.find(g=>g.category===null&&g.start===510)!;
assert.ok(morningGap);
assert.deepEqual([morningGap.start,morningGap.end,morningGap.title],[510,690,'未安排']);
const draft=draftInGap(routineDay,morningGap)!;
assert.ok(draft);assert.notEqual(draft.id,morningGap.id);
assert.deepEqual([draft.start,draft.end,draft.title,draft.done],[510,690,'',false]);
assert.equal(JSON.stringify(routineDay),routineBefore,'Opening or discarding a draft must not mutate saved data');
const partialDay:Day={...routineDay,blocks:[...routineDay.blocks,{...draft,title:'Research',end:570}]};
assert.equal(daySchema.safeParse(partialDay).success,true);
assert.deepEqual(dayOverview(partialDay,defaults)[0].groups.filter(g=>g.category===null).map(g=>[g.start,g.end]),[[570,690]]);
const middleDay:Day={...routineDay,blocks:[...routineDay.blocks,{...draft,title:'Research',start:540,end:600}]};
assert.deepEqual(dayOverview(middleDay,defaults)[0].groups.filter(g=>g.category===null).map(g=>[g.start,g.end]),[[510,540],[600,690]]);
const fullDay:Day={...routineDay,blocks:[...routineDay.blocks,{...draft,title:'Research'}]};
assert.equal(daySchema.safeParse(fullDay).success,true);
assert.equal(dayOverview(fullDay,defaults)[0].groups.filter(g=>g.category===null).length,0);
assert.equal(draftInGap(partialDay,morningGap),null,'Stale gaps must not open an overlapping draft');
for(const range of [{start:510,end:510},{start:-1,end:30},{start:2800,end:2881},{start:510.5,end:600}])assert.equal(draftInGap(routineDay,range),null);
const clippedGap=dayOverview(spanning,defaults).find(p=>p.id==='afternoon')!.groups.find(g=>g.category===null)!;
assert.deepEqual([clippedGap.start,clippedGap.end],[810,1080]);
assert.deepEqual(editedBlockTimes(clippedGap,'13:30','18:00',450),{start:810,end:1080});
assert.deepEqual(editedBlockTimes({start:1800,end:1890},'06:00','07:30',450),{start:1800,end:1890});
assert.deepEqual(editedBlockTimes({start:1380,end:1500},'23:00','01:00',450),{start:1380,end:1500});
assert.deepEqual(editedBlockTimes({start:450,end:1890},'07:30','07:30',450),{start:450,end:1890});
assert.deepEqual(editedBlockTimes(morningGap,'09:00','10:00',450),{start:540,end:600});
assert.equal(JSON.stringify(routineDay),routineBefore);
console.log('PASS: gap drafts prefill without saving, partial scheduling preserves remaining gaps, stale gaps are rejected, and overnight editor times retain their day offset');
